"""Unit tests for the pure entity-resolution functions (no DB required)."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.services import entity_resolution as er

PERSONS = [
    {"person_id": "P1", "full_name": "Rahul Kumar Sharma", "aliases": "R. Sharma|Rahul Sharma|Deva",
     "address": "Flat 3B, Shrivardhan Apartments"},
    {"person_id": "P2", "full_name": "Priya Nair", "aliases": "",
     "address": "Flat 3B, Shrivardhan Apartments"},
    {"person_id": "P3", "full_name": "Rohit Sharma", "aliases": "",
     "address": "12 Some Other Road"},
]


def test_phone_normalization():
    for raw in ["+91 90000 14417", "9000014417", "09000014417", "+919000014417",
                "91-90000-14417", "0091 9000014417", "(9000) 014417"]:
        assert er.normalize_phone(raw) == "+919000014417"
    assert er.normalize_phone(None) is None
    assert er.normalize_phone("") is None
    assert er.normalize_phone("abc") is None
    assert er.is_plausible_phone("+919000014417") is True
    assert er.is_plausible_phone("+9112345") is False


def test_name_normalization():
    assert er.normalize_name("Smt. Sulabha  Chaudhari") == "sulabha chaudhari"
    assert er.normalize_name("R. Nagvekar") == "r nagvekar"
    assert er.normalize_name(None) == ""
    assert er.name_variants("Rahul Kumar Sharma") == {
        "rahul kumar sharma", "rahul sharma", "r sharma", "r k sharma"
    }


def test_alias_index():
    idx = er.build_alias_index(PERSONS)
    assert er.resolve_alias("Rahul Kumar Sharma", idx) == "P1"
    assert er.resolve_alias("R. Sharma", idx) == "P1"
    assert er.resolve_alias("Rahul Sharma", idx) == "P1"
    assert er.resolve_alias("r  sharma", idx) == "P1"
    assert er.resolve_alias("Rohit Sharma", idx) == "P3"
    assert er.resolve_alias("Nobody Here", idx) is None
    assert er.resolve_alias_verbose("Nobody Here", idx)[1] == "NO_MATCH"
    assert er.resolve_alias_verbose("R. Sharma", idx) == ("P1", "MATCH")

    # ambiguity: two people whose generated variants collide must not resolve
    amb = er.build_alias_index([
        {"person_id": "A", "full_name": "Sunil Mehta", "aliases": ""},
        {"person_id": "B", "full_name": "Sanjay Mehta", "aliases": ""},
    ])
    assert er.resolve_alias("S. Mehta", amb) is None
    assert er.resolve_alias_verbose("S. Mehta", amb)[1] == "AMBIGUOUS"
    assert er.resolve_alias("Sunil Mehta", amb) == "A"


def test_free_text_mention_scan():
    idx = er.build_alias_index(PERSONS)
    hits = er.find_alias_mentions(
        "The complainant states that one R. Sharma was seen with Rohit Sharma near the market.", idx)
    assert {p for _, p in hits} == {"P1", "P3"}
    assert er.find_alias_mentions("nothing here", idx) == []


def test_sim_mismatch():
    idx = er.build_alias_index(PERSONS)
    names = {"P1": "Rahul Kumar Sharma", "P2": "Priya Nair", "P3": "Rohit Sharma"}

    same = er.detect_sim_name_mismatch(
        {"phone_id": "PH1", "number": "+919000000001", "owner_person_id": "P1",
         "sim_registered_name": "Rahul Kumar Sharma"}, names, idx)
    assert same is None

    alias_form = er.detect_sim_name_mismatch(
        {"phone_id": "PH2", "number": "+919000000002", "owner_person_id": "P1",
         "sim_registered_name": "R. Sharma"}, names, idx)
    assert alias_form is None

    # explicit alias not generated by name_variants (e.g. "Deva") must NOT flag as third party
    explicit_alias = er.detect_sim_name_mismatch(
        {"phone_id": "PH2B", "number": "+919000000022", "owner_person_id": "P1",
         "sim_registered_name": "Deva"}, names, idx)
    assert explicit_alias is None

    third = er.detect_sim_name_mismatch(
        {"phone_id": "PH3", "number": "+919000000003", "owner_person_id": "P1",
         "sim_registered_name": "Priya Nair"}, names, idx)
    assert third["kind"] == "SIM_REGISTERED_TO_THIRD_PARTY"
    assert third["registered_person_id"] == "P2"
    assert third["actual_owner_person_id"] == "P1"

    unknown = er.detect_sim_name_mismatch(
        {"phone_id": "PH4", "number": "+919000000004", "owner_person_id": "P1",
         "sim_registered_name": "Some Walk-In Name"}, names, idx)
    assert unknown["kind"] == "SIM_REGISTERED_TO_UNKNOWN_NAME"
    assert unknown["registered_person_id"] is None


def test_shared_address():
    cands = er.shared_address_candidates(PERSONS)
    assert len(cands) == 1
    assert (cands[0]["person_a"], cands[0]["person_b"]) == ("P1", "P2")
    assert cands[0]["confidence"] <= 0.25
    assert cands[0]["requires_human_review"] is True
    assert "flat" not in er.normalize_address("Flat 3B, Shrivardhan Apartments")
